pub mod error;
pub mod config;
pub mod request;
pub mod event;
pub mod schema;
pub mod protocol;
pub mod route;
pub mod transport;
pub mod framing;
pub mod auth;
pub mod endpoint;
pub mod provider;
pub mod tool_stream;
pub mod args_fixer;
pub mod lifecycle;
pub mod tool_runtime;
pub mod generate_object;
pub mod openai_chat;
pub mod actor;

// Re-export public API
pub use error::LlmError;
pub use config::merge_config;
pub use request::{LlmRequest, CanonicalRequest};
pub use event::{LlmEvent, LlmResponse, Usage, StreamStats};
pub use schema::{ToolDefinition, ToolChoice};
pub use protocol::{Protocol, StreamState};
pub use route::Route;
pub use transport::HttpTransport;
pub use framing::decode_sse_chunk;
pub use auth::{Auth, BearerAuth, NoneAuth};
pub use endpoint::Endpoint;
pub use provider::ProviderConfig;
pub use tool_stream::ToolStream;
pub use args_fixer::{fix_args_string, repair_tool_call, repair_tool_calls};
pub use lifecycle::StreamLifecycle;
pub use tool_runtime::{Tool, ToolRuntime};
pub use generate_object::GenerateObject;
pub use openai_chat::OpenAIChatProtocol;
pub use actor::LlmActor;
